### ISSUE TITLE
Dataset structure

### ISSUE THREAD

**Issue by raduslmn** [mhashas/Document-Image-Unwarping-pytorch#3]
There are 3 different datasets one can use for training: 
1. DOCUNET
2. DOCUNET_IM2IM
3. DOCUNET_INVERTED
Could you explain or give examples for how their data should be structured?

For example, i notice that DOCUNET dataset requires 2 folders for training `deformed_labels_64x64`  with .jpg (DEFORMED_EXT) files and `inverted_vf_64x64` with .mat (VECTOR_FIELD_EXT) files.
Now i have about 200k images of flatbed scanned documents i can use for training.  How do i go about preparing/creating these files so that they can be used for training?

**Comment by mhashas** [comment]
Hi, thanks for the interest. I suggest having a look at (http://openaccess.thecvf.com/content_cvpr_2018/html/Ma_DocUNet_Document_Image_CVPR_2018_paper.html) if you have not already done it. The dataset that they show there is the docunet dataset. The input for the different 3 datasets is always the deformed image. What differs is the output that we are predicting.

1. DOCUNET -> predicting the deformation field. This deformation field was used to go from a flat image to a deformed image. When flattening our deformed image, we need to invert this vector field and apply it to our deformed image. This is a post-processing step and since the vector field can be a matrix up to 512x512, it can end up being costly in terms of time.
2. DOCUNET_IM2IM -> predicting the pixel values of the flat image directly. Disregards the vector field completely and casts the problem as image 2 image translation 
3. DOCUNET_INVERTED -> predicts the inverted deformation field, the main advantage is that we no longer need the postprocessing step of finding the inverse of our vector field matrix. 

To answer your question: If you have 200k image of flatbed scanned documents, you would need the code to deform these images. This code takes as input a flat image and outputs 2 things: the deformed image and the deformation field that was used to deform the image. If you use the deformed image and the deformation field you get 1, if you use the deformed image and the original flat image you get 2, if you use the deformed image and the inverted deformation field you get 3.

I hope this answers your question. Unfortunately, it is not possible for me to make available the source code for obtaining the deformed images and vector fields. The authors explain in their paper the mathematics behind creating this deformation field, so you could try out. Let me know if you have other questions.

**Comment by mhashas** [comment]
@raduslmn Here you can view a toy example of the dataset https://drive.google.com/file/d/16Ay3NVzFmsVe1saMOZam-9nHBE0xcmyA/view?usp=sharing
